### ISSUE TITLE
Bug: attachment filestreams not closed in case of error

### ISSUE THREAD

**Issue by rogierschouten** [nodemailer/nodemailer-smtp-transport#18]
Hi,

I can't seem to reproduce this reliably but if the nodemailer gets an ECONNREFUSED error, the fs.ReadStreams that were passed as attachments are not always closed when the sendMail callback is invoked. This causes EPERM errors later on when I try to unlink the file

```javascript
var path = require("path");
var fs = require("fs");
var nodemailer = require("nodemailer");
var smtpPool = require("nodemailer-smtp-pool");

var testFile = path.join(__dirname, "some_file.txt");

// non existing server
var transporter = nodemailer.createTransport(smtpPool( {
	host: "127.0.0.1",
	port: 1237,
	auth: {
		user: "pietje",
		pass: "puk"
	}
}));
transporter.sendMail({
	from: "somebody@someserver.com",
	replyTo: "somebody@someserver.com",
	to: ["somebody@someserver.com"],
	subject: "subject",
	text: "body",
	attachments: [{ filename: path.basename(testFile), content: fs.createReadStream(testFile, {flags: "r"}) }]
}, function(error, info) {
	transporter.close();
      // HERE, the attachment readstream is NOT closed
});

```

**Comment by andris9** [comment]
Sorry for ignoring this issue for so long. I don't know a good solution here. If something fails, then opened streams are left unconsumed and thus 'end' never fires. Not all streams are equal either, some stream types have `abort()` method, some have `close()`, some have nothing to close them. Trying to consume the stream to the end might not be a good idea either in case it is a large data stream from some slow source. So I would leave the clean up for sending app, since Nodemailer itself does not know enough about the type of the stream and how to properly close it. I'm going to add a not to the docs about it.

**Comment by rogierschouten** [comment]
Is there a way for the outside world to know then whether the stream has ended when something goes wrong?
